name: Test All Bash Scripts

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm sudo git base-devel curl shellcheck
          useradd -m testuser
          echo 'testuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set permissions
        run: |
          chown -R testuser:testuser .

      - name: Run shellcheck
        run: |
          find . -type f -name "*.sh" -exec shellcheck {} \;

      - name: Run scripts as non-root user
        run: |
          su testuser -c '
            chmod +x $(find . -type f -name "*.sh")
            find . -type f -name "*.sh" | while read -r script; do
              echo "[ EXEC ] Running $script"
              timeout 60s bash "$script" || echo "[ WARN ] $script failed or timed out"
            done
          '
