name: Test All Bash Scripts

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:latest  # Gunakan Void jika mau, atau buat Dockerfile sendiri

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm bash git curl sudo shellcheck

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find and lint all Bash scripts
        run: |
          echo "[ INFO ] Running ShellCheck on all bash scripts..."
          find . -type f -name "*.sh" -o -exec grep -Iq bash {} \; | while read -r script; do
            echo "[ CHECK ] $script"
            shellcheck "$script"
          done

      - name: Run all Bash scripts (test execution)
        run: |
          echo "[ INFO ] Running all bash scripts (non-interactive, test mode)..."
          chmod +x $(find . -type f -name "*.sh")
          find . -type f -name "*.sh" | while read -r script; do
            echo "[ EXEC ] Running $script"
            timeout 30s bash "$script" || echo "[ WARN ] $script failed or timed out"
          done
